In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import pandas
data = pandas.read_csv('/content/drive/MyDrive/Health Disease Risk assessment/input/diabetes.csv');

In [ ]:
import pandas as pd
from sklearn import model_selection
import os
os.chdir("/content/drive/MyDrive/Health Disease Risk assessment/src")

import config

print(config)

import os
os.chdir(config.SAVE_TRAINING_FILE_WITH_FOLDS)

if __name__ == "__main__":
    # Training data is in a csv file called train.csv
    df = data

    # we create a new column called kfold and fill it with -1
    df["kfold"] = -1

    # the next step is to randomize the rows of the data
    df = df.sample(frac=1).reset_index(drop=True)

    # fetch targets
    y = df.Outcome.values

    # initiate the kfold class from model_selection module
    kf = model_selection.StratifiedKFold(n_splits=5)

    # fill the new kfold column
    for f, (t_, v_) in enumerate(kf.split(X=df, y=y)):
      df.loc[v_, 'kfold'] = f

    # save the new csv with kfold column
    df.to_csv("diabetes_folds.csv", index=False)

<module 'config' from '/content/drive/MyDrive/Health Disease Risk assessment/src/config.py'>

In [ ]:
data1 = pandas.read_csv("/content/drive/MyDrive/Health Disease Risk assessment/input/diabetes_folds.csv")

In [ ]:
data1.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,kfold
0,2,99,52,15,94,24.6,0.637,21,0,0
1,1,128,88,39,110,36.5,1.057,37,1,0
2,4,132,86,31,0,28.0,0.419,63,0,0
3,6,115,60,39,0,33.7,0.245,40,1,0
4,1,89,24,19,25,27.8,0.559,21,0,0

In [ ]:
data1['kfold'].value_counts()

kfold
0    154
1    154
2    154
3    153
4    153
Name: count, dtype: int64

In [ ]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.11/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from catboost) (1.13.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (3.2.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly->catboost) (9.0.0)
Downloading catboost-1.2.8-cp311-cp311-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 7.3 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8

In [ ]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from sklearn.metrics import f1_score
import pickle

import os
os.chdir("/content/drive/MyDrive/Health Disease Risk assessment/src")

from config import TRAINING_FILE_WITH_FOLDS, MODEL_OUTPUT
import model_dispacher, param_distributions  # assumes model_dispatcher.py renamed to models.py

from model_dispacher import models
from param_distributions import param_distributions

# Load the dataset with folds
data = pd.read_csv(TRAINING_FILE_WITH_FOLDS)

# Tune model using RandomizedSearchCV
def tune_model(model_name, X, y):
    model = models[model_name]
    if model_name in param_distributions:
        search = RandomizedSearchCV(
            estimator=model,
            param_distributions=param_distributions[model_name],
            n_iter=10,
            cv=5,
            scoring='f1',
            random_state=42,
            n_jobs=-1
        )
        search.fit(X, y)
        return search.best_estimator_, search.best_params_
    else:
        model.fit(X, y)
        return model, None

# Evaluate model on each fold
def evaluate_model_on_folds(model, model_name):
    f1_scores = []
    for fold in range(5):
        df_train = data[data.kfold != fold].reset_index(drop=True)
        df_valid = data[data.kfold == fold].reset_index(drop=True)

        X_train = df_train.drop(["Outcome", "kfold"], axis=1).values
        y_train = df_train.Outcome.values
        X_valid = df_valid.drop(["Outcome", "kfold"], axis=1).values
        y_valid = df_valid.Outcome.values

        model.fit(X_train, y_train)
        preds = model.predict(X_valid)
        f1 = f1_score(y_valid, preds)
        print(f"📁 Fold {fold}: F1 Score = {f1:.4f}")
        f1_scores.append(f1)

    avg_f1 = sum(f1_scores) / len(f1_scores)
    print(f"🎯 Avg F1 Score for {model_name}: {avg_f1:.4f}")
    return avg_f1, f1_scores

if __name__ == "__main__":
    X = data.drop("Outcome", axis=1).values
    y = data.Outcome.values

    best_overall_model = None
    best_overall_score = 0
    best_overall_model_name = ""
    best_overall_params = None

    for model_name in models.keys():
        print(f"\n🔍 Tuning model: {model_name}")
        best_model, best_params = tune_model(model_name, X, y)
        print(f"✅ Best Params: {best_params if best_params else 'Default'}")

        print(f"📊 Evaluating {model_name} on each fold...")
        avg_f1, _ = evaluate_model_on_folds(best_model, model_name)

        if avg_f1 > best_overall_score:
            best_overall_score = avg_f1
            best_overall_model = best_model
            best_overall_model_name = model_name
            best_overall_params = best_params

    # Save the best overall model
    final_model_path = f"{MODEL_OUTPUT}/{best_overall_model_name}_BEST.pkl"
    with open(final_model_path, "wb") as f:
        pickle.dump(best_overall_model, f)

    print(f"\n🏆 Best Overall Model: {best_overall_model_name}")
    print(f"💯 Best F1 Score: {best_overall_score:.4f}")
    print(f"🧪 Best Params: {best_overall_params if best_overall_params else 'Default'}")
    print(f"💾 Model saved to {final_model_path}")

🔍 Tuning model: decision_tree_gini
✅ Best Params: {'min_samples_split': 2, 'min_samples_leaf': 2, 'max_depth': 5}
📊 Evaluating decision_tree_gini on each fold...
📁 Fold 0: F1 Score = 0.7222
📁 Fold 1: F1 Score = 0.5918
📁 Fold 2: F1 Score = 0.6078
📁 Fold 3: F1 Score = 0.6087
📁 Fold 4: F1 Score = 0.6061
🎯 Avg F1 Score for decision_tree_gini: 0.6273

🔍 Tuning model: decision_tree_entropy
✅ Best Params: {'min_samples_split': 10, 'min_samples_leaf': 4, 'max_depth': 5}
📊 Evaluating decision_tree_entropy on each fold...
📁 Fold 0: F1 Score = 0.6316
📁 Fold 1: F1 Score = 0.6019
📁 Fold 2: F1 Score = 0.6379
📁 Fold 3: F1 Score = 0.6486
📁 Fold 4: F1 Score = 0.6476
🎯 Avg F1 Score for decision_tree_entropy: 0.6335

🔍 Tuning model: random_forest
✅ Best Params: {'n_estimators': 100, 'min_samples_split': 5, 'max_depth': None}
📊 Evaluating random_forest on each fold...
📁 Fold 0: F1 Score = 0.6517
📁 Fold 1: F1 Score = 0.5941
📁 Fold 2: F1 Score = 0.6327
📁 Fold 3: F1 Score = 0.5794
📁 Fold 4: F1 Score = 0.6863
🎯 Avg F1 Score for random_forest: 0.6288

🔍 Tuning model: gradient_boosting
✅ Best Params: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.2}
📊 Evaluating gradient_boosting on each fold...
📁 Fold 0: F1 Score = 0.6733
📁 Fold 1: F1 Score = 0.5941
📁 Fold 2: F1 Score = 0.6296
📁 Fold 3: F1 Score = 0.6415
📁 Fold 4: F1 Score = 0.6667
🎯 Avg F1 Score for gradient_boosting: 0.6410

🔍 Tuning model: extra_trees
✅ Best Params: {'n_estimators': 200, 'min_samples_split': 5, 'max_depth': 10}
📊 Evaluating extra_trees on each fold...
📁 Fold 0: F1 Score = 0.5783
📁 Fold 1: F1 Score = 0.5393
📁 Fold 2: F1 Score = 0.6067
📁 Fold 3: F1 Score = 0.6383
📁 Fold 4: F1 Score = 0.7010
🎯 Avg F1 Score for extra_trees: 0.6127

🔍 Tuning model: ada_boost

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

✅ Best Params: {'n_estimators': 100, 'learning_rate': 1}
📊 Evaluating ada_boost on each fold...
📁 Fold 0: F1 Score = 0.5882
📁 Fold 1: F1 Score = 0.6263
📁 Fold 2: F1 Score = 0.6296
📁 Fold 3: F1 Score = 0.5905
📁 Fold 4: F1 Score = 0.7115
🎯 Avg F1 Score for ada_boost: 0.6292

🔍 Tuning model: knn
✅ Best Params: {'weights': 'distance', 'p': 1, 'n_neighbors': 9}
📊 Evaluating knn on each fold...
📁 Fold 0: F1 Score = 0.4819
📁 Fold 1: F1 Score = 0.6000
📁 Fold 2: F1 Score = 0.6019
📁 Fold 3: F1 Score = 0.5872
📁 Fold 4: F1 Score = 0.6600
🎯 Avg F1 Score for knn: 0.5862

🔍 Tuning model: logistic_regression

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
20 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py", line 1203, in fit
    raise ValueError("l1_ratio must be specified when penalty is elasticnet.")
ValueError: l1_ratio must be specified when penalty is elasticnet.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.38491863 0.38491863 0.35474453        nan        nan        nan
 0.38491863        nan 0.38491863 0.38491863]
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 3 is smaller than n_iter=10. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

✅ Best Params: {'solver': 'saga', 'penalty': 'l2', 'C': 10}
📊 Evaluating logistic_regression on each fold...
📁 Fold 0: F1 Score = 0.2338
📁 Fold 1: F1 Score = 0.3855
📁 Fold 2: F1 Score = 0.4419
📁 Fold 3: F1 Score = 0.4667
📁 Fold 4: F1 Score = 0.3768
🎯 Avg F1 Score for logistic_regression: 0.3809

🔍 Tuning model: svm_linear
✅ Best Params: {'C': 10}
📊 Evaluating svm_linear on each fold...
📁 Fold 0: F1 Score = 0.5682
📁 Fold 1: F1 Score = 0.5918
📁 Fold 2: F1 Score = 0.5714
📁 Fold 3: F1 Score = 0.6667
📁 Fold 4: F1 Score = 0.7573
🎯 Avg F1 Score for svm_linear: 0.6311

🔍 Tuning model: svm_rbf

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

✅ Best Params: {'gamma': 'scale', 'C': 10}
📊 Evaluating svm_rbf on each fold...
📁 Fold 0: F1 Score = 0.5610
📁 Fold 1: F1 Score = 0.5376
📁 Fold 2: F1 Score = 0.5684
📁 Fold 3: F1 Score = 0.6275
📁 Fold 4: F1 Score = 0.7158
🎯 Avg F1 Score for svm_rbf: 0.6021

🔍 Tuning model: naive_bayes
✅ Best Params: Default
📊 Evaluating naive_bayes on each fold...
📁 Fold 0: F1 Score = 0.6186
📁 Fold 1: F1 Score = 0.5714
📁 Fold 2: F1 Score = 0.6095
📁 Fold 3: F1 Score = 0.6481
📁 Fold 4: F1 Score = 0.6602
🎯 Avg F1 Score for naive_bayes: 0.6216

🔍 Tuning model: xgboost

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 1 is smaller than n_iter=10. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

✅ Best Params: {'subsample': 1.0, 'n_estimators': 100, 'max_depth': 5, 'learning_rate': 0.1}
📊 Evaluating xgboost on each fold...
📁 Fold 0: F1 Score = 0.7000
📁 Fold 1: F1 Score = 0.6126
📁 Fold 2: F1 Score = 0.6481
📁 Fold 3: F1 Score = 0.6111
📁 Fold 4: F1 Score = 0.6667
🎯 Avg F1 Score for xgboost: 0.6477

🔍 Tuning model: lightgbm

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Number of positive: 268, number of negative: 500
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000179 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 769
[LightGBM] [Info] Number of data points in the train set: 768, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.348958 -> initscore=-0.623621
[LightGBM] [Info] Start training from score -0.623621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
✅ Best Params: {'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.01}
📊 Evaluating lightgbm on each fold...
[LightGBM] [Info] Number of positive: 214, number of negative: 400
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000086 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 666
[LightGBM] [Info] Number of data points in the train set: 614, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.348534 -> initscore=-0.625489
[LightGBM] [Info] Start training from score -0.625489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

📁 Fold 1: F1 Score = 0.6186
[LightGBM] [Info] Number of positive: 214, number of negative: 400
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000126 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 658
[LightGBM] [Info] Number of data points in the train set: 614, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.348534 -> initscore=-0.625489
[LightGBM] [Info] Start training from score -0.625489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
📁 Fold 2: F1 Score = 0.6604
[LightGBM] [Info] Number of positive: 215, number of negative: 400
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000132 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 663
[LightGBM] [Info] Number of data points in the train set: 615, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.349593 -> initscore=-0.620827
[LightGBM] [Info] Start training from score -0.620827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
📁 Fold 3: F1 Score = 0.6408
[LightGBM] [Info] Number of positive: 215, number of negative: 400
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000121 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 669
[LightGBM] [Info] Number of data points in the train set: 615, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.349593 -> initscore=-0.620827
[LightGBM] [Info] Start training from score -0.620827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

📁 Fold 4: F1 Score = 0.6602
🎯 Avg F1 Score for lightgbm: 0.6387

🔍 Tuning model: catboost
0:	learn: 0.6434659	total: 1.46ms	remaining: 145ms
1:	learn: 0.6067543	total: 2.57ms	remaining: 126ms
2:	learn: 0.5798995	total: 3.41ms	remaining: 110ms
3:	learn: 0.5526245	total: 4.21ms	remaining: 101ms
4:	learn: 0.5321820	total: 5ms	remaining: 94.9ms
5:	learn: 0.5168417	total: 5.86ms	remaining: 91.9ms
6:	learn: 0.5020907	total: 6.61ms	remaining: 87.8ms
7:	learn: 0.4920803	total: 7.4ms	remaining: 85.1ms
8:	learn: 0.4817336	total: 8.21ms	remaining: 83ms
9:	learn: 0.4746973	total: 9.03ms	remaining: 81.3ms
10:	learn: 0.4677496	total: 9.86ms	remaining: 79.8ms
11:	learn: 0.4612871	total: 10.7ms	remaining: 78.1ms
12:	learn: 0.4554428	total: 11.5ms	remaining: 77ms
13:	learn: 0.4511102	total: 12.3ms	remaining: 75.3ms
14:	learn: 0.4462688	total: 13.1ms	remaining: 74.4ms
15:	learn: 0.4381853	total: 13.9ms	remaining: 72.8ms
16:	learn: 0.4344813	total: 14.7ms	remaining: 71.7ms
17:	learn: 0.4305062	total: 15.7ms	remaining: 71.4ms
18:	learn: 0.4253393	total: 16.6ms	remaining: 70.7ms
19:	learn: 0.4232080	total: 17.3ms	remaining: 69.3ms
20:	learn: 0.4192839	total: 18.2ms	remaining: 68.3ms
21:	learn: 0.4166617	total: 18.9ms	remaining: 67ms
22:	learn: 0.4129374	total: 19.7ms	remaining: 65.9ms
23:	learn: 0.4099174	total: 20.5ms	remaining: 64.9ms
24:	learn: 0.4078670	total: 21.4ms	remaining: 64.3ms
25:	learn: 0.4047794	total: 22.2ms	remaining: 63.3ms
26:	learn: 0.4023304	total: 23ms	remaining: 62.2ms
27:	learn: 0.4008661	total: 23.8ms	remaining: 61.3ms
28:	learn: 0.3989096	total: 24.7ms	remaining: 60.4ms
29:	learn: 0.3957946	total: 25.5ms	remaining: 59.4ms
30:	learn: 0.3922410	total: 26.3ms	remaining: 58.5ms
31:	learn: 0.3905360	total: 27ms	remaining: 57.3ms
32:	learn: 0.3888785	total: 27.7ms	remaining: 56.2ms
33:	learn: 0.3873020	total: 28.5ms	remaining: 55.3ms
34:	learn: 0.3842107	total: 29.3ms	remaining: 54.4ms
35:	learn: 0.3821896	total: 30ms	remaining: 53.4ms
36:	learn: 0.3803097	total: 30.8ms	remaining: 52.5ms
37:	learn: 0.3788063	total: 31.6ms	remaining: 51.6ms
38:	learn: 0.3767781	total: 32.4ms	remaining: 50.6ms
39:	learn: 0.3750299	total: 33.1ms	remaining: 49.7ms
40:	learn: 0.3726183	total: 34ms	remaining: 48.9ms
41:	learn: 0.3711024	total: 34.7ms	remaining: 47.9ms
42:	learn: 0.3684631	total: 35.5ms	remaining: 47.1ms
43:	learn: 0.3672107	total: 36.3ms	remaining: 46.2ms
44:	learn: 0.3649591	total: 37.1ms	remaining: 45.3ms
45:	learn: 0.3636033	total: 37.8ms	remaining: 44.4ms
46:	learn: 0.3613376	total: 38.6ms	remaining: 43.5ms
47:	learn: 0.3598229	total: 39.5ms	remaining: 42.7ms
48:	learn: 0.3574100	total: 40.2ms	remaining: 41.9ms
49:	learn: 0.3559292	total: 41ms	remaining: 41ms
50:	learn: 0.3546104	total: 41.8ms	remaining: 40.2ms
51:	learn: 0.3523392	total: 42.6ms	remaining: 39.3ms
52:	learn: 0.3495253	total: 43.3ms	remaining: 38.4ms
53:	learn: 0.3471785	total: 44.1ms	remaining: 37.6ms
54:	learn: 0.3459681	total: 44.9ms	remaining: 36.8ms
55:	learn: 0.3436510	total: 45.7ms	remaining: 35.9ms
56:	learn: 0.3419599	total: 46.5ms	remaining: 35.1ms
57:	learn: 0.3409092	total: 47.3ms	remaining: 34.3ms
58:	learn: 0.3385496	total: 48ms	remaining: 33.4ms
59:	learn: 0.3374388	total: 48.8ms	remaining: 32.5ms
60:	learn: 0.3356645	total: 49.6ms	remaining: 31.7ms
61:	learn: 0.3349164	total: 50.4ms	remaining: 30.9ms
62:	learn: 0.3330512	total: 51.1ms	remaining: 30ms
63:	learn: 0.3327126	total: 51.8ms	remaining: 29.2ms
64:	learn: 0.3312657	total: 52.7ms	remaining: 28.4ms
65:	learn: 0.3281312	total: 53.5ms	remaining: 27.6ms
66:	learn: 0.3271590	total: 54.3ms	remaining: 26.8ms
67:	learn: 0.3254859	total: 55.1ms	remaining: 25.9ms
68:	learn: 0.3247717	total: 55.9ms	remaining: 25.1ms
69:	learn: 0.3226007	total: 56.7ms	remaining: 24.3ms
70:	learn: 0.3212930	total: 57.5ms	remaining: 23.5ms
71:	learn: 0.3202410	total: 58.2ms	remaining: 22.6ms
72:	learn: 0.3189840	total: 59.2ms	remaining: 21.9ms
73:	learn: 0.3172271	total: 60ms	remaining: 21.1ms
74:	learn: 0.3145321	total: 60.7ms	remaining: 20.2ms
75:	learn: 0.3130859	total: 61.5ms	remaining: 19.4ms
76:	learn: 0.3122915	total: 62.3ms	remaining: 18.6ms
77:	learn: 0.3103151	total: 63ms	remaining: 17.8ms
78:	learn: 0.3076953	total: 63.8ms	remaining: 17ms
79:	learn: 0.3065380	total: 64.6ms	remaining: 16.1ms
80:	learn: 0.3055408	total: 65.4ms	remaining: 15.3ms
81:	learn: 0.3033466	total: 66.2ms	remaining: 14.5ms
82:	learn: 0.3030842	total: 67ms	remaining: 13.7ms
83:	learn: 0.3024989	total: 67.7ms	remaining: 12.9ms
84:	learn: 0.3013269	total: 68.5ms	remaining: 12.1ms
85:	learn: 0.3005393	total: 69.2ms	remaining: 11.3ms
86:	learn: 0.3002641	total: 70ms	remaining: 10.5ms
87:	learn: 0.2996085	total: 70.7ms	remaining: 9.64ms
88:	learn: 0.2987305	total: 71.5ms	remaining: 8.83ms
89:	learn: 0.2966071	total: 72.2ms	remaining: 8.02ms
90:	learn: 0.2956375	total: 72.9ms	remaining: 7.21ms
91:	learn: 0.2932259	total: 73.7ms	remaining: 6.41ms
92:	learn: 0.2925903	total: 74.5ms	remaining: 5.6ms
93:	learn: 0.2918434	total: 75.2ms	remaining: 4.8ms
94:	learn: 0.2893602	total: 76ms	remaining: 4ms
95:	learn: 0.2877913	total: 76.8ms	remaining: 3.2ms
96:	learn: 0.2875381	total: 77.5ms	remaining: 2.4ms
97:	learn: 0.2865735	total: 78.3ms	remaining: 1.6ms
98:	learn: 0.2854480	total: 79.1ms	remaining: 798us
99:	learn: 0.2847569	total: 79.8ms	remaining: 0us
✅ Best Params: {'learning_rate': 0.2, 'iterations': 100, 'depth': 5}
📊 Evaluating catboost on each fold...
0:	learn: 0.6428930	total: 1.04ms	remaining: 103ms
1:	learn: 0.6024410	total: 1.89ms	remaining: 92.9ms
2:	learn: 0.5759613	total: 2.91ms	remaining: 94.2ms
3:	learn: 0.5528523	total: 3.66ms	remaining: 87.9ms
4:	learn: 0.5351526	total: 4.44ms	remaining: 84.3ms
5:	learn: 0.5221018	total: 5.25ms	remaining: 82.3ms
6:	learn: 0.5098896	total: 6.02ms	remaining: 80ms
7:	learn: 0.5003265	total: 6.77ms	remaining: 77.9ms
8:	learn: 0.4919306	total: 7.53ms	remaining: 76.2ms
9:	learn: 0.4823970	total: 8.26ms	remaining: 74.3ms
10:	learn: 0.4751220	total: 8.99ms	remaining: 72.7ms
11:	learn: 0.4702827	total: 9.68ms	remaining: 71ms
12:	learn: 0.4633546	total: 10.4ms	remaining: 69.4ms
13:	learn: 0.4573238	total: 11.1ms	remaining: 68.2ms
14:	learn: 0.4522908	total: 11.8ms	remaining: 67.1ms
15:	learn: 0.4451637	total: 12.6ms	remaining: 66.3ms
16:	learn: 0.4412654	total: 13.3ms	remaining: 65ms
17:	learn: 0.4396938	total: 14.1ms	remaining: 64.1ms
18:	learn: 0.4358829	total: 14.8ms	remaining: 63.1ms
19:	learn: 0.4320497	total: 15.5ms	remaining: 62.1ms
20:	learn: 0.4292948	total: 16.3ms	remaining: 61.3ms
21:	learn: 0.4261268	total: 17.1ms	remaining: 60.5ms
22:	learn: 0.4239892	total: 17.8ms	remaining: 59.7ms
23:	learn: 0.4207783	total: 18.6ms	remaining: 58.9ms
24:	learn: 0.4186771	total: 19.3ms	remaining: 57.9ms
25:	learn: 0.4167498	total: 21.7ms	remaining: 61.6ms
26:	learn: 0.4131278	total: 22.5ms	remaining: 60.8ms
27:	learn: 0.4110951	total: 23.3ms	remaining: 59.8ms
28:	learn: 0.4086289	total: 24ms	remaining: 58.8ms
29:	learn: 0.4049859	total: 24.9ms	remaining: 58.1ms
30:	learn: 0.4026743	total: 25.7ms	remaining: 57.2ms
31:	learn: 0.4005268	total: 26.7ms	remaining: 56.8ms
32:	learn: 0.3984025	total: 27.5ms	remaining: 55.8ms
33:	learn: 0.3967346	total: 28.2ms	remaining: 54.7ms
34:	learn: 0.3924760	total: 29ms	remaining: 53.9ms
35:	learn: 0.3901683	total: 29.8ms	remaining: 53ms
36:	learn: 0.3871355	total: 30.9ms	remaining: 52.7ms
37:	learn: 0.3851402	total: 31.9ms	remaining: 52.1ms
38:	learn: 0.3824658	total: 32.8ms	remaining: 51.2ms
39:	learn: 0.3803911	total: 33.5ms	remaining: 50.2ms
40:	learn: 0.3793287	total: 36.1ms	remaining: 51.9ms
41:	learn: 0.3774039	total: 37ms	remaining: 51ms
42:	learn: 0.3750569	total: 37.9ms	remaining: 50.2ms
43:	learn: 0.3725282	total: 38.6ms	remaining: 49.2ms
44:	learn: 0.3696819	total: 39.5ms	remaining: 48.3ms
45:	learn: 0.3669618	total: 40.6ms	remaining: 47.6ms
46:	learn: 0.3656016	total: 42ms	remaining: 47.4ms
47:	learn: 0.3640388	total: 43.4ms	remaining: 47ms
48:	learn: 0.3620348	total: 44.5ms	remaining: 46.3ms
49:	learn: 0.3610677	total: 45.2ms	remaining: 45.2ms
50:	learn: 0.3604366	total: 46.1ms	remaining: 44.3ms
51:	learn: 0.3595569	total: 46.9ms	remaining: 43.3ms
52:	learn: 0.3584493	total: 48.4ms	remaining: 42.9ms
53:	learn: 0.3566820	total: 49.7ms	remaining: 42.3ms
54:	learn: 0.3538936	total: 50.5ms	remaining: 41.3ms
55:	learn: 0.3531168	total: 51.5ms	remaining: 40.5ms
56:	learn: 0.3515932	total: 52.2ms	remaining: 39.4ms
57:	learn: 0.3512368	total: 53ms	remaining: 38.3ms
58:	learn: 0.3501491	total: 53.7ms	remaining: 37.3ms
59:	learn: 0.3485845	total: 54.5ms	remaining: 36.3ms
60:	learn: 0.3463168	total: 55.2ms	remaining: 35.3ms
61:	learn: 0.3459792	total: 55.9ms	remaining: 34.3ms
62:	learn: 0.3456669	total: 56.7ms	remaining: 33.3ms
63:	learn: 0.3453740	total: 57.5ms	remaining: 32.3ms
64:	learn: 0.3451661	total: 58.2ms	remaining: 31.3ms
65:	learn: 0.3441941	total: 59ms	remaining: 30.4ms
66:	learn: 0.3435157	total: 59.7ms	remaining: 29.4ms
67:	learn: 0.3426519	total: 60.5ms	remaining: 28.5ms
68:	learn: 0.3416846	total: 61.2ms	remaining: 27.5ms
69:	learn: 0.3394235	total: 61.9ms	remaining: 26.5ms
70:	learn: 0.3374553	total: 62.7ms	remaining: 25.6ms
71:	learn: 0.3370073	total: 63.4ms	remaining: 24.7ms
72:	learn: 0.3350045	total: 64.1ms	remaining: 23.7ms
73:	learn: 0.3340530	total: 64.8ms	remaining: 22.8ms
74:	learn: 0.3332387	total: 65.7ms	remaining: 21.9ms
75:	learn: 0.3329827	total: 66.4ms	remaining: 21ms
76:	learn: 0.3312718	total: 67.3ms	remaining: 20.1ms
77:	learn: 0.3307649	total: 68ms	remaining: 19.2ms
78:	learn: 0.3303673	total: 68.6ms	remaining: 18.2ms
79:	learn: 0.3299078	total: 69.3ms	remaining: 17.3ms
80:	learn: 0.3276977	total: 70.1ms	remaining: 16.4ms
81:	learn: 0.3260319	total: 70.8ms	remaining: 15.5ms
82:	learn: 0.3257643	total: 71.5ms	remaining: 14.7ms
83:	learn: 0.3223450	total: 72.3ms	remaining: 13.8ms
84:	learn: 0.3205135	total: 72.9ms	remaining: 12.9ms
85:	learn: 0.3184366	total: 73.7ms	remaining: 12ms
86:	learn: 0.3168635	total: 74.4ms	remaining: 11.1ms
87:	learn: 0.3166468	total: 75.2ms	remaining: 10.2ms
88:	learn: 0.3154592	total: 75.8ms	remaining: 9.37ms
89:	learn: 0.3139206	total: 76.5ms	remaining: 8.5ms
90:	learn: 0.3138530	total: 77.2ms	remaining: 7.64ms
91:	learn: 0.3131103	total: 78ms	remaining: 6.78ms
92:	learn: 0.3126955	total: 78.7ms	remaining: 5.92ms
93:	learn: 0.3119027	total: 79.5ms	remaining: 5.07ms
94:	learn: 0.3116701	total: 80.1ms	remaining: 4.22ms
95:	learn: 0.3093159	total: 80.8ms	remaining: 3.37ms
96:	learn: 0.3091982	total: 81.5ms	remaining: 2.52ms
97:	learn: 0.3075547	total: 82.5ms	remaining: 1.68ms
98:	learn: 0.3062963	total: 83.2ms	remaining: 840us
99:	learn: 0.3038999	total: 84ms	remaining: 0us
📁 Fold 0: F1 Score = 0.6444
0:	learn: 0.6376226	total: 922us	remaining: 91.4ms
1:	learn: 0.5937203	total: 1.72ms	remaining: 84.3ms
2:	learn: 0.5595613	total: 2.53ms	remaining: 81.8ms
3:	learn: 0.5372268	total: 3.27ms	remaining: 78.5ms
4:	learn: 0.5175530	total: 4.02ms	remaining: 76.4ms
5:	learn: 0.5030194	total: 4.81ms	remaining: 75.3ms
6:	learn: 0.4896758	total: 5.59ms	remaining: 74.3ms
7:	learn: 0.4789593	total: 6.32ms	remaining: 72.7ms
8:	learn: 0.4680172	total: 7.05ms	remaining: 71.3ms
9:	learn: 0.4581984	total: 7.79ms	remaining: 70.1ms
10:	learn: 0.4513065	total: 8.54ms	remaining: 69.1ms
11:	learn: 0.4445681	total: 9.46ms	remaining: 69.3ms
12:	learn: 0.4382019	total: 10.3ms	remaining: 68.8ms
13:	learn: 0.4340548	total: 11.2ms	remaining: 68.8ms
14:	learn: 0.4277625	total: 11.9ms	remaining: 67.7ms
15:	learn: 0.4229636	total: 12.7ms	remaining: 66.9ms
16:	learn: 0.4186717	total: 13.5ms	remaining: 66ms
17:	learn: 0.4144959	total: 14.3ms	remaining: 64.9ms
18:	learn: 0.4107503	total: 15ms	remaining: 63.8ms
19:	learn: 0.4068889	total: 15.8ms	remaining: 63.2ms
20:	learn: 0.4037534	total: 16.5ms	remaining: 62.1ms
21:	learn: 0.4009018	total: 17.3ms	remaining: 61.5ms
22:	learn: 0.3986530	total: 20.8ms	remaining: 69.7ms
23:	learn: 0.3961195	total: 21.7ms	remaining: 68.7ms
24:	learn: 0.3929564	total: 22.5ms	remaining: 67.5ms
25:	learn: 0.3907598	total: 23.3ms	remaining: 66.3ms
26:	learn: 0.3885678	total: 24.1ms	remaining: 65.2ms
27:	learn: 0.3863620	total: 24.9ms	remaining: 64ms
28:	learn: 0.3836865	total: 25.6ms	remaining: 62.7ms
29:	learn: 0.3811786	total: 26.4ms	remaining: 61.6ms
30:	learn: 0.3787474	total: 27.1ms	remaining: 60.4ms
31:	learn: 0.3743753	total: 27.9ms	remaining: 59.3ms
32:	learn: 0.3732130	total: 28.6ms	remaining: 58.1ms
33:	learn: 0.3711276	total: 29.3ms	remaining: 57ms
34:	learn: 0.3686411	total: 30.1ms	remaining: 55.9ms
35:	learn: 0.3656647	total: 30.9ms	remaining: 54.9ms
36:	learn: 0.3618359	total: 31.7ms	remaining: 53.9ms
37:	learn: 0.3589221	total: 32.4ms	remaining: 52.9ms
38:	learn: 0.3572267	total: 33.2ms	remaining: 52ms
39:	learn: 0.3558250	total: 34ms	remaining: 51ms
40:	learn: 0.3536350	total: 34.8ms	remaining: 50ms
41:	learn: 0.3516219	total: 35.5ms	remaining: 49ms
42:	learn: 0.3495641	total: 36.2ms	remaining: 48ms
43:	learn: 0.3487727	total: 36.9ms	remaining: 47ms
44:	learn: 0.3474083	total: 37.7ms	remaining: 46ms
45:	learn: 0.3466704	total: 38.8ms	remaining: 45.6ms
46:	learn: 0.3457635	total: 39.6ms	remaining: 44.6ms
47:	learn: 0.3452993	total: 40.3ms	remaining: 43.6ms
48:	learn: 0.3413429	total: 41ms	remaining: 42.7ms
49:	learn: 0.3377569	total: 41.8ms	remaining: 41.8ms
50:	learn: 0.3363737	total: 42.4ms	remaining: 40.8ms
51:	learn: 0.3353492	total: 43.1ms	remaining: 39.8ms
52:	learn: 0.3350642	total: 43.9ms	remaining: 38.9ms
53:	learn: 0.3338576	total: 44.6ms	remaining: 38ms
54:	learn: 0.3317789	total: 45.4ms	remaining: 37.1ms
55:	learn: 0.3309108	total: 46ms	remaining: 36.2ms
56:	learn: 0.3304964	total: 46.8ms	remaining: 35.3ms
57:	learn: 0.3301299	total: 47.5ms	remaining: 34.4ms
58:	learn: 0.3283506	total: 48.2ms	remaining: 33.5ms
59:	learn: 0.3281498	total: 48.9ms	remaining: 32.6ms
60:	learn: 0.3279937	total: 49.6ms	remaining: 31.7ms
61:	learn: 0.3246720	total: 50.3ms	remaining: 30.9ms
62:	learn: 0.3232672	total: 51.1ms	remaining: 30ms
63:	learn: 0.3226320	total: 51.7ms	remaining: 29.1ms
64:	learn: 0.3216341	total: 52.4ms	remaining: 28.2ms
65:	learn: 0.3166992	total: 53.2ms	remaining: 27.4ms
66:	learn: 0.3161724	total: 54ms	remaining: 26.6ms
67:	learn: 0.3149242	total: 54.8ms	remaining: 25.8ms
68:	learn: 0.3141967	total: 55.5ms	remaining: 25ms
69:	learn: 0.3136196	total: 56.3ms	remaining: 24.1ms
70:	learn: 0.3101612	total: 57ms	remaining: 23.3ms
71:	learn: 0.3089154	total: 57.6ms	remaining: 22.4ms
72:	learn: 0.3075155	total: 58.4ms	remaining: 21.6ms
73:	learn: 0.3072690	total: 59.1ms	remaining: 20.8ms
74:	learn: 0.3060896	total: 59.9ms	remaining: 20ms
75:	learn: 0.3048643	total: 60.7ms	remaining: 19.2ms
76:	learn: 0.3028432	total: 61.3ms	remaining: 18.3ms
77:	learn: 0.3019183	total: 62.8ms	remaining: 17.7ms
78:	learn: 0.3000261	total: 63.5ms	remaining: 16.9ms
79:	learn: 0.2979557	total: 64.2ms	remaining: 16ms
80:	learn: 0.2971384	total: 64.9ms	remaining: 15.2ms
81:	learn: 0.2941980	total: 65.7ms	remaining: 14.4ms
82:	learn: 0.2934912	total: 66.5ms	remaining: 13.6ms
83:	learn: 0.2925569	total: 67.2ms	remaining: 12.8ms
84:	learn: 0.2904079	total: 68ms	remaining: 12ms
85:	learn: 0.2896779	total: 68.8ms	remaining: 11.2ms
86:	learn: 0.2869268	total: 69.5ms	remaining: 10.4ms
87:	learn: 0.2858281	total: 70.3ms	remaining: 9.59ms
88:	learn: 0.2855063	total: 71ms	remaining: 8.78ms
89:	learn: 0.2841306	total: 71.7ms	remaining: 7.97ms
90:	learn: 0.2835574	total: 72.4ms	remaining: 7.16ms
91:	learn: 0.2801059	total: 73.1ms	remaining: 6.35ms
92:	learn: 0.2795603	total: 73.8ms	remaining: 5.55ms
93:	learn: 0.2791486	total: 74.5ms	remaining: 4.75ms
94:	learn: 0.2778372	total: 75.3ms	remaining: 3.96ms
95:	learn: 0.2774749	total: 76ms	remaining: 3.16ms
96:	learn: 0.2765446	total: 76.7ms	remaining: 2.37ms
97:	learn: 0.2764364	total: 77.4ms	remaining: 1.58ms
98:	learn: 0.2763418	total: 78.1ms	remaining: 788us
99:	learn: 0.2755054	total: 78.9ms	remaining: 0us
📁 Fold 1: F1 Score = 0.5743
0:	learn: 0.6400102	total: 884us	remaining: 87.6ms
1:	learn: 0.5982911	total: 1.79ms	remaining: 87.7ms
2:	learn: 0.5658424	total: 2.63ms	remaining: 85.2ms
3:	learn: 0.5446180	total: 3.39ms	remaining: 81.3ms
4:	learn: 0.5237860	total: 4.17ms	remaining: 79.2ms
5:	learn: 0.5101917	total: 4.95ms	remaining: 77.5ms
6:	learn: 0.4979562	total: 5.72ms	remaining: 76.1ms
7:	learn: 0.4858727	total: 6.48ms	remaining: 74.5ms
8:	learn: 0.4762694	total: 7.2ms	remaining: 72.8ms
9:	learn: 0.4674291	total: 7.96ms	remaining: 71.7ms
10:	learn: 0.4585262	total: 8.64ms	remaining: 69.9ms
11:	learn: 0.4510473	total: 9.35ms	remaining: 68.6ms
12:	learn: 0.4435653	total: 10.1ms	remaining: 67.7ms
13:	learn: 0.4381035	total: 10.9ms	remaining: 66.8ms
14:	learn: 0.4333375	total: 11.6ms	remaining: 65.8ms
15:	learn: 0.4300842	total: 12.4ms	remaining: 65.1ms
16:	learn: 0.4273905	total: 13.2ms	remaining: 64.3ms
17:	learn: 0.4223073	total: 14ms	remaining: 63.6ms
18:	learn: 0.4166192	total: 14.7ms	remaining: 62.7ms
19:	learn: 0.4142334	total: 15.4ms	remaining: 61.7ms
20:	learn: 0.4113112	total: 16.1ms	remaining: 60.7ms
21:	learn: 0.4087744	total: 16.8ms	remaining: 59.7ms
22:	learn: 0.4046350	total: 17.6ms	remaining: 59ms
23:	learn: 0.4014101	total: 18.3ms	remaining: 58.1ms
24:	learn: 0.3994200	total: 19.1ms	remaining: 57.2ms
25:	learn: 0.3975698	total: 19.8ms	remaining: 56.4ms
26:	learn: 0.3956370	total: 20.5ms	remaining: 55.5ms
27:	learn: 0.3928989	total: 21.3ms	remaining: 54.7ms
28:	learn: 0.3892199	total: 22ms	remaining: 53.9ms
29:	learn: 0.3872629	total: 22.8ms	remaining: 53.2ms
30:	learn: 0.3852007	total: 24.7ms	remaining: 55ms
31:	learn: 0.3822403	total: 25.5ms	remaining: 54.1ms
32:	learn: 0.3807134	total: 26.6ms	remaining: 54ms
33:	learn: 0.3794903	total: 27.5ms	remaining: 53.5ms
34:	learn: 0.3782564	total: 28.6ms	remaining: 53.1ms
35:	learn: 0.3757587	total: 29.5ms	remaining: 52.4ms
36:	learn: 0.3740821	total: 30.6ms	remaining: 52ms
37:	learn: 0.3706750	total: 31.3ms	remaining: 51.1ms
38:	learn: 0.3690755	total: 32.1ms	remaining: 50.2ms
39:	learn: 0.3668956	total: 32.8ms	remaining: 49.2ms
40:	learn: 0.3660021	total: 33.6ms	remaining: 48.3ms
41:	learn: 0.3637406	total: 34.3ms	remaining: 47.4ms
42:	learn: 0.3611956	total: 35.1ms	remaining: 46.5ms
43:	learn: 0.3593453	total: 35.8ms	remaining: 45.6ms
44:	learn: 0.3561805	total: 37.2ms	remaining: 45.4ms
45:	learn: 0.3537490	total: 38.7ms	remaining: 45.4ms
46:	learn: 0.3513258	total: 39.9ms	remaining: 45ms
47:	learn: 0.3505363	total: 40.7ms	remaining: 44.1ms
48:	learn: 0.3472093	total: 41.5ms	remaining: 43.2ms
49:	learn: 0.3448801	total: 42.3ms	remaining: 42.3ms
50:	learn: 0.3395993	total: 43ms	remaining: 41.3ms
51:	learn: 0.3380710	total: 43.8ms	remaining: 40.4ms
52:	learn: 0.3350574	total: 44.5ms	remaining: 39.5ms
53:	learn: 0.3344272	total: 45.3ms	remaining: 38.6ms
54:	learn: 0.3322665	total: 46.1ms	remaining: 37.7ms
55:	learn: 0.3313160	total: 46.8ms	remaining: 36.8ms
56:	learn: 0.3306691	total: 47.5ms	remaining: 35.8ms
57:	learn: 0.3301860	total: 48.2ms	remaining: 34.9ms
58:	learn: 0.3257793	total: 49ms	remaining: 34ms
59:	learn: 0.3251857	total: 49.7ms	remaining: 33.2ms
60:	learn: 0.3228373	total: 50.4ms	remaining: 32.3ms
61:	learn: 0.3218951	total: 52.1ms	remaining: 31.9ms
62:	learn: 0.3208059	total: 52.8ms	remaining: 31ms
63:	learn: 0.3203983	total: 53.6ms	remaining: 30.1ms
64:	learn: 0.3201853	total: 54.4ms	remaining: 29.3ms
65:	learn: 0.3172150	total: 55.1ms	remaining: 28.4ms
66:	learn: 0.3155316	total: 55.9ms	remaining: 27.5ms
67:	learn: 0.3128647	total: 56.6ms	remaining: 26.7ms
68:	learn: 0.3107857	total: 57.3ms	remaining: 25.8ms
69:	learn: 0.3094052	total: 58.1ms	remaining: 24.9ms
70:	learn: 0.3086238	total: 58.9ms	remaining: 24ms
71:	learn: 0.3079645	total: 59.6ms	remaining: 23.2ms
72:	learn: 0.3076227	total: 60.3ms	remaining: 22.3ms
73:	learn: 0.3072641	total: 61ms	remaining: 21.4ms
74:	learn: 0.3048068	total: 61.8ms	remaining: 20.6ms
75:	learn: 0.3043982	total: 62.5ms	remaining: 19.7ms

In [ ]:
import pickle

with open('/content/drive/MyDrive/Health Disease Risk assessment/Models/catboost_BEST.pkl', 'rb') as file:
    model = pickle.load(file)

In [ ]:
data

array([[  1.   , 180.   ,   0.   , ...,   0.282,  41.   ,   1.   ],
       [  2.   , 121.   ,  70.   , ...,   0.886,  23.   ,   0.   ],
       [  0.   , 129.   ,  80.   , ...,   0.703,  29.   ,   0.   ],
       ...,
       [  0.   ,  57.   ,  60.   , ...,   0.735,  67.   ,   0.   ],
       [  2.   ,  89.   ,  90.   , ...,   0.292,  42.   ,   0.   ],
       [  8.   , 197.   ,  74.   , ...,   1.191,  39.   ,   1.   ]])

In [ ]:
data = data.values

In [ ]:
data = data.drop("Outcome", axis=1).values

In [ ]:
data

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
data[1]

array([ 1.   , 85.   , 66.   , 29.   ,  0.   , 26.6  ,  0.351, 31.   ,
        0.   ])

In [ ]:
# prompt: convert a list into numpy array

import numpy as np

# Assuming 'data' is your pandas DataFrame and you want to convert a specific column to a NumPy array
# Example: Convert the first row of 'data' to a NumPy array.
numpy_array = np.array(data[1])

print(numpy_array)
print(type(numpy_array))

In [ ]:
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [ ]:
data

array(None, dtype=object)

In [ ]:
import numpy as np
model.predict(np.array(data))

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])